/**
 * Generates the procedural sprite sheet: one rigged SVG per character & monster.
 * Output is a TS module committed to the repo so the app has ZERO binary image assets
 * (perfect for the offline APK, and fully scalable on any screen).
 */
import fs from 'node:fs';
import path from 'node:path';
import { buildSpriteSVG } from '../src/game/sprite/build';
import { CHARACTERS } from '../src/game/data/characters';
import { MONSTERS } from '../src/game/data/monsters';
import type { SpriteSpec } from '../src/game/types';

const outDir = path.resolve(process.cwd(), 'src/game/sprite');
const map: Record<string, string> = {};
const specs: Record<string, SpriteSpec> = {};

for (const c of CHARACTERS) {
  map[c.id] = buildSpriteSVG(c.art);
  specs[c.id] = c.art;
}
for (const m of MONSTERS) {
  map[m.id] = buildSpriteSVG(m.art);
  specs[m.id] = m.art;
}

const file = path.join(outDir, 'generated.ts');
const header = `/* AUTO-GENERATED by scripts/generate-sprites.ts — do not edit by hand. */
import type { SpriteSpec } from '../types';

/** rigged SVG markup keyed by character/monster definition id */
export const SPRITES: Record<string, string> = ${JSON.stringify(map)};

export const SPRITE_SPECS: Record<string, SpriteSpec> = ${JSON.stringify(specs)};
`;
fs.writeFileSync(file, header, 'utf8');
const bytes = Buffer.byteLength(header, 'utf8');
console.log(`[sprites] wrote ${path.relative(process.cwd(), file)} — ${Object.keys(map).length} sprites, ${(bytes / 1024).toFixed(1)} KB`);

// also drop a standalone preview HTML for eyeballing
const previewDir = path.resolve(process.cwd(), 'public');
fs.mkdirSync(previewDir, { recursive: true });
const cards = Object.entries(map).map(([id, svg]) => `<figure data-id="${id}"><div class="s">${svg}</div><figcaption>${id}</figcaption></figure>`).join('\n');
fs.writeFileSync(path.join(previewDir, 'sprite-preview.html'), `<!doctype html><html><head><meta charset="utf-8"><title>VAIN sprites</title>
<style>body{background:#0a0813;color:#ddd;font:12px ui-monospace,monospace;margin:0;padding:16px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px}
figure{margin:0;background:linear-gradient(180deg,#161128,#05040a);border:1px solid #2a2140;border-radius:10px;padding:6px;text-align:center}
figcaption{opacity:.7;font-size:10px}
svg{width:100%;height:auto;transform-origin:50% 100%;transition:transform .2s}
body [data-pose="attack"] .rig-armR{transform:rotate(-120deg)}
</style></head><body><h3>VAIN — procedural sprites (${Object.keys(map).length})</h3><div class="grid">${cards}</div></body></html>`, 'utf8');
console.log('[sprites] preview: public/sprite-preview.html');
